#!/bin/bash

# Main vars for configuration
DIARIO=${HOME}/diario/

function packages-list-update () {
    FILE="${DIARIO}/packages-list"

    if [ -d "${DIARIO}" ] ; then
	COLUMNS=132 dpkg --list > "${FILE}"
    fi

}

function partition-update () {
    FDISK=/sbin/fdisk
    CP=/bin/cp
    FILEPART=${DIARIO}/part-list
    FILEFSTAB=${DIARIO}/fstab

    > ${FILEPART}
    for disk in hda hdb hdc hdd hde hdf hdg hdh sda sdb sdc sdd sde sdf sdg sdh cciss/c?d? cciss/disc?/disc ; do
	fdisk -l /dev/${disk} >> ${FILEPART} 2>/dev/null
    done
    
    ${CP} /etc/fstab ${FILEFSTAB}
}

function lvm-update () {
    VGDISPLAY=/sbin/vgdisplay
    FILELVM=${DIARIO}/lvm-list
    > ${FILELVM}

    ${VGDISPLAY} --short >> ${FILELVM} 2>&1
    ${VGDISPLAY} --verbose >> ${FILELVM} 2>&1
}

function md-update () {
    MDADM=/sbin/mdadm
    FILEMD=${DIARIO}/md-list
    > ${FILEMD}
    
    mdadm --detail /dev/md* >> ${FILEMD} 2>&1
    cat-file /proc/mdstat      ${FILEMD}
}

# $1 - procfile
# $2 - File to log
function cat-file () {
    CAT=/bin/cat

    echo $1 >> $2
    if [ -e $1 ] ; then
	${CAT} $1 >> $2
    else
	echo "$1 don't exist" >> $2
    fi
    echo >> $2
}

function kernel-update () {
    FILEKERNEL=${DIARIO}/kernel-list
    CAT=/bin/cat
    LSMOD=/sbin/lsmod

    >${FILEKERNEL}
    cat-file /proc/version  ${FILEKERNEL}
    cat-file /proc/cmdline  ${FILEKERNEL}
    cat-file /proc/devices  ${FILEKERNEL}
    ${LSMOD}             >> ${FILEKERNEL}
    echo                 >> ${FILEKERNEL}
    cat-file /proc/fb       ${FILEKERNEL}
    cat-file /proc/locks    ${FILEKERNEL}
    cat-file /proc/lvm/global ${FILEKERNEL}
    cat-file /proc/swaps    ${FILEKERNEL}
    cat-file /proc/filesystems ${FILEKERNEL}
    echo "OpenAFS client" >> ${FILEKERNEL}
    rxdebug localhost 7001 -version >> ${FILEKERNEL}
    cmdebug localhost -cache >> ${FILEKERNEL}
}

function hardware-update () {
    LSPCI=/usr/bin/lspci
    HDPARM=/sbin/hdparm
    FILEPCI=${DIARIO}/pci-list
    FILEALSA=${DIARIO}/alsa-list
    FILEHARDWARE=${DIARIO}/hardware-list
    FILEHDPARM=${DIARIO}/hdparm-list
    HPADUCLI=/usr/sbin/hpaducli
    HPASMCLI=/sbin/hpasmcli
    
    > ${FILEPCI}
    echo "#################### lspci "       >> ${FILEPCI}
    ${LSPCI}           >> ${FILEPCI}
    echo "#################### lspci -tv"   >> ${FILEPCI}
    ${LSPCI} -tv       >> ${FILEPCI}
    echo "#################### lspci -v"    >> ${FILEPCI}
    ${LSPCI} -v        >> ${FILEPCI}
    echo "#################### lspci -vv"   >> ${FILEPCI}
    ${LSPCI} -vv       >> ${FILEPCI}
    cat-file /proc/pci    ${FILEPCI}
    ${LSPCI} -x         > ${FILEPCI}-x
    
    > ${FILEALSA}
    cat-file /proc/asound/version ${FILEALSA}
    cat-file /proc/asound/cards   ${FILEALSA}
    cat-file /proc/asound/devices ${FILEALSA}
    cat-file /proc/asound/modules ${FILEALSA}
    cat-file /proc/asound/pcm     ${FILEALSA}
    cat-file /proc/asound/timers  ${FILEALSA}

    > ${FILEHARDWARE}
    cat-file /proc/cpuinfo                ${FILEHARDWARE}
    cat-file /proc/dma                    ${FILEHARDWARE}
    cat-file /proc/interrupts             ${FILEHARDWARE}
    cat-file /proc/iomem                  ${FILEHARDWARE}
    cat-file /proc/ioports                ${FILEHARDWARE}
    cat-file /proc/device-tree/compatible ${FILEHARDWARE}
    echo                               >> ${FILEHARDWARE}
    cat-file /proc/device-tree/model      ${FILEHARDWARE}
    echo                               >> ${FILEHARDWARE}
    cat-file /proc/device-tree/serial-number  ${FILEHARDWARE}
    echo                               >> ${FILEHARDWARE}
    cat-file /proc/bus/input/devices      ${FILEHARDWARE}
    cat-file /proc/bus/ieee1394/devices   ${FILEHARDWARE}
    cat-file /proc/bus/usb/devices        ${FILEHARDWARE}
    cat-file /proc/bus/usb/drivers        ${FILEHARDWARE}
    cat-file /proc/ide/drivers            ${FILEHARDWARE}
    cat-file /proc/ide/via                ${FILEHARDWARE}
    cat-file /proc/ide/piix               ${FILEHARDWARE}
    cat-file /proc/ide/svwks              ${FILEHARDWARE}
    cat-file /proc/scsi/scsi              ${FILEHARDWARE}
    cat-file /proc/driver/cciss/cciss0    ${FILEHARDWARE}
    cat-file /proc/driver/cciss/cciss1    ${FILEHARDWARE}
    cat-file /proc/scsi/3w-xxxx/0         ${FILEHARDWARE}
    cat-file /proc/pmu/info               ${FILEHARDWARE}
    cat-file /proc/pmu/interrupts         ${FILEHARDWARE}
    cat-file /proc/pmu/options            ${FILEHARDWARE}
    cat-file /proc/dri/0/name             ${FILEHARDWARE}
    cat-file /proc/dri/0/mem              ${FILEHARDWARE}
    

    > ${FILEHDPARM}
    for disk in hda hdb hdc hdd hde hdf hdg hdh sda sdb sdc sdd sde sdf sdg sdh cciss/c?d? cciss/disc?/disc ; do
	${HDPARM}    /dev/${disk} >> ${FILEHDPARM} 2> /dev/null
	${HDPARM} -i /dev/${disk} >> ${FILEHDPARM} 2> /dev/null
	${HDPARM} -I /dev/${disk} >> ${FILEHDPARM} 2> /dev/null
    done
    
    ${HPADUCLI} -f ${DIARIO}/hpadu-report
    ${HPASMCLI} -s "SHOW ASR; SHOW BOOT; SHOW DIMM ; SHOW F1 ; SHOW FANS ; SHOW HT ; SHOW IML ; SHOW IPL ; SHOW NAME ; SHOW POWERSUPPLY ; SHOW PXE ; SHOW SERIAL  BIOS ;  SHOW SERIAL EMBEDDED ; SHOW SERIAL VIRTUAL ; SHOW SERVER ; SHOW TEMP ; ; SHOW WOL ;" > ${DIARIO}/hpasmcli-report < /dev/null

}

function net-update () {
    FILENET=${DIARIO}/net-list
    IFCONFIG=/sbin/ifconfig
    ROUTE=/sbin/route
    IP=/sbin/ip
    
    > ${FILENET}
    echo "ifconfig"        >> ${FILENET}
    ${IFCONFIG}            >> ${FILENET}
    echo "route"           >> ${FILENET}
    ${ROUTE}               >> ${FILENET}
    echo "route -A inet6"  >> ${FILENET}
    ${ROUTE} -A inet6      >> ${FILENET}
    echo "ip link"         >> ${FILENET}
    ${IP} link             >> ${FILENET}
    echo "ip addr"         >> ${FILENET}
    ${IP} addr             >> ${FILENET}
    echo "ip addr"         >> ${FILENET}
    ${IP} route            >> ${FILENET}
    echo "ip -6 route"     >> ${FILENET}
    ${IP} -6 route         >> ${FILENET}
    echo "ip tunnel"       >> ${FILENET}
    ${IP} tunnel           >> ${FILENET}
    cat-file /proc/net/dev    ${FILENET}
}


if [ -d ${DIARIO} ] ; then
    packages-list-update
    partition-update
    lvm-update
    md-update
    kernel-update
    hardware-update
    net-update
else
    echo "Don't exist ${DIARIO} directory, not running"
fi

